import { createAgent, tool } from "langchain";
import * as z from "zod";
import { OutputChannelLogger } from "../../logging/OutputChannelLogger";
import { Settings } from "../../config/Settings";
import { LearningLibrary, LearningCardRecord } from "../../learning/LearningLibrary";
import { LearningLevel } from "../../learning/LearningTopicStore";
import { createChatModel } from "../models/OllamaModelFactory";
import { runAgentWithBudget } from "./agentRun";

export interface LearningRunOptions {
  settings: Settings;
  library: LearningLibrary;
  logger: OutputChannelLogger;
  topicId: string;
  topic: string;
  level: LearningLevel;
  target: number;
  /** Concepts the learner marked "didn't know" — weak spots to focus on. */
  weakConcepts: string[];
  signal: AbortSignal;
  onSaved: (record: LearningCardRecord) => void;
}

const AGENT_BUDGET_MS = 120000;
const AGENT_RECURSION_LIMIT = 60;
const MAX_BODY = 320;
const MAX_EXAMPLE = 320;

const LEVEL_GUIDE: Record<LearningLevel, string> = {
  beginner:
    "Assume little prior knowledge. Explain foundational concepts and terminology plainly.",
  intermediate:
    "Assume working familiarity. Cover practical patterns, common gotchas, and how pieces fit together.",
  advanced:
    "Assume strong fundamentals. Cover internals, edge cases, performance, and nuanced trade-offs.",
};

/**
 * The learning "card team": a single agent that first outlines distinct concepts
 * for the topic at the chosen level, then writes and saves one concise card per
 * concept via the save_card tool. Content is generated by the local Ollama model
 * — there is no offline fallback (the service reports when the brain is absent).
 */
export async function runLearningCards(options: LearningRunOptions): Promise<number> {
  const { settings, library, logger, topicId, topic, level, target, weakConcepts, signal, onSaved } =
    options;
  let saved = 0;
  const focusCount = Math.round(target * 0.7);

  const known = await library.knownTitles(topicId);

  const saveTool = tool(
    async (input) => {
      const { title, body, example } = input as { title: string; body: string; example?: string };
      if (saved >= target) {
        return JSON.stringify({ saved: false, reason: "target reached" });
      }
      const clean = title.trim();
      if (!clean) {
        return JSON.stringify({ saved: false, reason: "empty title" });
      }
      if (known.has(clean.toLowerCase())) {
        return JSON.stringify({ saved: false, reason: "duplicate title" });
      }
      const record = await library.addCard({
        topicId,
        title: clean.slice(0, 90),
        body: body.trim().slice(0, MAX_BODY),
        example: example && example.trim() ? example.trim().slice(0, MAX_EXAMPLE) : undefined,
      });
      if (!record) {
        return JSON.stringify({ saved: false, reason: "already saved" });
      }
      known.add(clean.toLowerCase());
      saved += 1;
      onSaved(record);
      return JSON.stringify({ saved: true, remaining: target - saved });
    },
    {
      name: "save_card",
      description:
        "Save one concise learning card: a short concept title, a 1-3 sentence plain-text explanation, and an optional tiny code example.",
      schema: z.object({
        title: z.string().min(2).max(90).describe("A short concept name, e.g. 'Debouncing'"),
        body: z.string().min(10).max(320).describe("1-3 plain-text sentences explaining the concept"),
        example: z.string().max(320).optional().describe("Optional short code snippet (plain text)"),
      }),
    }
  );

  const agent = createAgent({ model: createChatModel(settings), tools: [saveTool] });

  const avoid = [...known].slice(0, 30);
  const weak = weakConcepts.slice(0, 20);
  const focusGuidance =
    weak.length > 0
      ? `The learner recently found these concepts unfamiliar: ${weak.join("; ")}. ` +
        `About ${focusCount} of the ${target} cards should build on or sit adjacent to those weak spots (go a little deeper, cover closely related ideas). ` +
        `The remaining cards should introduce fresh, varied concepts elsewhere in the topic to keep new material coming. `
      : "Spread the cards across genuinely different areas of the topic for good variety. ";

  await runAgentWithBudget({
    agent,
    messages: [
      {
        role: "system",
        content:
          "You are a tech tutor building a small deck of bite-sized learning cards for a developer on a short break. " +
          `Topic: "${topic}". Level: ${level}. ${LEVEL_GUIDE[level]} ` +
          `First outline ${target} distinct, genuinely useful concepts for this topic and level, then call save_card once for each. ` +
          focusGuidance +
          "Keep each card to ONE idea: a short title, a clear 1-3 sentence explanation in plain language, and a tiny code example only when it truly helps. " +
          "Be accurate — do not invent APIs. Avoid duplicates and the titles already saved. Stop once the target is reached.",
      },
      {
        role: "user",
        content:
          `Create and save ${target} ${level} learning cards about "${topic}".` +
          (weak.length ? ` Focus ~70% on the weak spots: ${weak.join("; ")}.` : "") +
          (avoid.length ? ` Already saved (do not repeat): ${avoid.join("; ")}.` : ""),
      },
    ],
    signal,
    budgetMs: AGENT_BUDGET_MS,
    recursionLimit: AGENT_RECURSION_LIMIT,
    savedSoFar: () => saved,
    logger,
    label: "Learning agent",
  });

  return saved;
}
